### ISSUE TITLE
Line dash example throws errors

### ISSUE THREAD

**Issue by hanbyul-here** [tangrams/blocks#2]
[This Tangram Play](https://mapzen.com/tangram/play/?scene=https%3A%2F%2Ftangrams.github.io%2Ftangram-sandbox%2Fstyles%2Felevation.yaml&lines=59-63#14/9.7363/8.5158) which is linked as an example of [lines-dash](http://tangrams.github.io/blocks/#lines-dash) throws errors. ( `Request error with a status of Bad Request` )  It seems like a api-key related problem.

**Comment by meetar** [comment]
I think this is an issue with https://github.com/tangrams/tangram-sandbox/ – the url is getting two api_key params:

`https://vector.mapzen.com/osm/all/14/8581/7747.topojson?api_key=vector-tiles-JUsa0Gc&api_key=vector-tiles-P6dkVl4`

I see that the `JUsa0Gc` key is in https://github.com/tangrams/tangram-sandbox/blob/77ba38df18bd90282f059f131bab8e52b711f2ae/styles/default.yaml as:

```
url_params:
    api_key: vector-tiles-JUsa0Gc
```

Maybe that's being merged in along with a source whose url already includes a key param?

**Comment by patriciogonzalezvivo** [comment]
Hi! yes we were brain storming with @bcamper on this one and I accidentally merge it
