### ISSUE TITLE
missing URL to Shaders in README.md

### ISSUE THREAD

**Issue by skorasaurus** [tangrams/blocks#3]
Hi, 

I was learning about shaders and their use in tangrams and [line 42](https://github.com/tangrams/blocks/blame/gh-pages/README.md#L42) - [Shaders inside Tangram read this documentation]. - appears to be missing a URL as it appears to be an incomplete link.

**Comment by patriciogonzalezvivo** [comment]
Thanks! hopefully fixed here https://github.com/tangrams/blocks/commit/cdd79dff9b701740d5705660175599960ac5b84d
